version: '3'

services:

  nginx:
    image: nginx
    container_name: covidtest_nginx
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./helper/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
      - ./logs/:/var/log/nginx
    depends_on:
      - web
    networks:
      main:
          aliases:
              - nginx

  postgres:
    restart: always
    image: postgres:10
    container_name: covidtest_postgres
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - postgres

  web:
    build:
      context: .
    container_name: covidtest_app
    command: sh -c './startup.sh'
    restart: always
    ports:
        - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - static_volume:/project/static
      - media_volume:/project/media
      - ./logs/django:/project/django.log
    env_file: .env
    links:
      - postgres
    networks:
        main:
            aliases:
                - web

networks:
  main:

volumes:
  static_volume:
  media_volume:
